# Generated by Django 4.1.6 on 2023-02-15 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_created_at_alter_user_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='competition',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 6, 43, 7, 736979)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 6, 43, 7, 736979)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 6, 43, 7, 736979)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 6, 43, 7, 736979)),
        ),
    ]
