# Generated by Django 4.1.6 on 2023-02-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_competition_user_id_alter_competition_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=models.CharField(default='c', max_length=500),
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.CharField(default='b', max_length=100),
        ),
    ]
