# Generated by Django 4.1.6 on 2023-02-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_competition_description_alter_competition_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
